services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: OpenRental-Booking
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5436:5432"
  openrental-booking:
    image: openrental-booking:1.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    ports:
      - "8081:8080"

