spring:
  application:
    name: openrental-booking
  datasource:
    url: jdbc:postgresql://${PGSQL_SERVICE_HOST}:${PGSQL_SERVICE_PORT}/OpenRental-Booking
    username: postgres
    password: ${postgres-password}
