spring:
  application:
    name: openrental-booking
  datasource:
    url: jdbc:postgresql://localhost:5432/OpenRental-Booking
    username: postgres
    password: ${postgres-password:postgres}
server:
  port: 8081
services:
  vehicles:
    url: http://localhost:8080
