spring:
  application:
    name: openrental-booking
  datasource:
    url: jdbc:postgresql://localhost:5432/openrental_booking
    username: postgres
server:
  port: 8081
services:
  vehicles:
    url: http://localhost:8080
